
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ActionType
    {
        Action_Action = 0,
        Action_Debug = 1,
        TriggerAction_AddTrigger = 2,
        TriggerAction_RemoveTrigger = 3,
        TriggerAction_ExcuteTrigger = 4,
        TriggerAction_AddBuff = 5,
        TriggerAction_RemoveBuff = 6,
        BuffAction_AddProp = 7,
    }

} 

