
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ActivityConfig : Luban.BeanBase
{
    public ActivityConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        ActivityType = (ActivityType)_buf.ReadInt();
        FunctionUnlockType = (FunctionUnlockType)_buf.ReadInt();
        Icon = _buf.ReadString();
        Name = _buf.ReadString();
        Sort = _buf.ReadInt();
        UIType = (UIType)_buf.ReadInt();
    }

    public static ActivityConfig DeserializeActivityConfig(ByteBuf _buf)
    {
        return new ActivityConfig(_buf);
    }

    public readonly int ID;
    /// <summary>
    /// 活动类型
    /// </summary>
    public readonly ActivityType ActivityType;
    /// <summary>
    /// 条件组合
    /// </summary>
    public readonly FunctionUnlockType FunctionUnlockType;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int Sort;
    /// <summary>
    /// 对应UI
    /// </summary>
    public readonly UIType UIType;
   
    public const int __ID__ = 431122257;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ActivityType:" + ActivityType + ","
        + "FunctionUnlockType:" + FunctionUnlockType + ","
        + "Icon:" + Icon + ","
        + "Name:" + Name + ","
        + "Sort:" + Sort + ","
        + "UIType:" + UIType + ","
        + "}";
    }
}

}

