
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum AttrEnum
    {
        Hp = 1,
        Mp = 2,
        Atk = 3,
        Def = 4,
        MoveSpeed = 5,
    }

} 

