
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Buff : Luban.BeanBase
{
    public Buff(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Priority = _buf.ReadInt();
        Limit = _buf.ReadInt();
        CountType = (CommonHandleType1)_buf.ReadInt();
        Count = _buf.ReadInt();
        TotalTime = _buf.ReadFloat();
        CDTime = _buf.ReadFloat();
        Condition = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Action = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Action.Add(_e0);}}
    }

    public static Buff DeserializeBuff(ByteBuf _buf)
    {
        return new Buff(_buf);
    }

    public readonly int ID;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 数量限制
    /// </summary>
    public readonly int Limit;
    /// <summary>
    /// 达到次数处理方式
    /// </summary>
    public readonly CommonHandleType1 CountType;
    /// <summary>
    /// 可触发次数<br/>0无限次触发<br/>-1不触发
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 生效时间
    /// </summary>
    public readonly float TotalTime;
    /// <summary>
    /// 冷却时间
    /// </summary>
    public readonly float CDTime;
    /// <summary>
    /// 条件组合
    /// </summary>
    public readonly string Condition;
    /// <summary>
    /// 触发行为
    /// </summary>
    public readonly System.Collections.Generic.List<int> Action;
   
    public const int __ID__ = 2081907;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Priority:" + Priority + ","
        + "Limit:" + Limit + ","
        + "CountType:" + CountType + ","
        + "Count:" + Count + ","
        + "TotalTime:" + TotalTime + ","
        + "CDTime:" + CDTime + ","
        + "Condition:" + Condition + ","
        + "Action:" + Luban.StringUtil.CollectionToString(Action) + ","
        + "}";
    }
}
}

