
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial struct color32
{
    public color32(ByteBuf _buf) 
    {
        R = _buf.ReadByte();
        G = _buf.ReadByte();
        B = _buf.ReadByte();
        A = _buf.ReadByte();
    }

    public static color32 Deserializecolor32(ByteBuf _buf)
    {
        return new color32(_buf);
    }

    public readonly byte R;
    public readonly byte G;
    public readonly byte B;
    public readonly byte A;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "r:" + R + ","
        + "g:" + G + ","
        + "b:" + B + ","
        + "a:" + A + ","
        + "}";
    }
}
}

