
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ConditionType
    {
        Condition_Action = 0,
        TriggerCondition_Random = 1,
        TriggerCondition_AccCount = 2,
        FunctionUnlockCondition_Lv = 3,
    }

} 

