
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ConstConfig : Luban.BeanBase
{
    public ConstConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        BattleConst = global::cfg.BattleConst.DeserializeBattleConst(_buf);
    }

    public static ConstConfig DeserializeConstConfig(ByteBuf _buf)
    {
        return new ConstConfig(_buf);
    }

    public readonly int ID;
    public readonly BattleConst BattleConst;
   
    public const int __ID__ = -1271334811;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        BattleConst?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "BattleConst:" + BattleConst + ","
        + "}";
    }
}
}

