
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class DeviceInfo : Luban.BeanBase
{
    public DeviceInfo(ByteBuf _buf) 
    {
        Name = _buf.ReadString();
        Lv = _buf.ReadInt();
        SupportES3 = _buf.ReadBool();
    }

    public static DeviceInfo DeserializeDeviceInfo(ByteBuf _buf)
    {
        return new DeviceInfo(_buf);
    }

    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 设备分级
    /// </summary>
    public readonly int Lv;
    /// <summary>
    /// 是否支持opgngles3
    /// </summary>
    public readonly bool SupportES3;
   
    public const int __ID__ = -1520650172;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Lv:" + Lv + ","
        + "SupportES3:" + SupportES3 + ","
        + "}";
    }
}

}
