
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class FunctionUnlockConfig : Luban.BeanBase
{
    public FunctionUnlockConfig(ByteBuf _buf) 
    {
        FunctionUnlockType = (FunctionUnlockType)_buf.ReadInt();
        Condition = _buf.ReadString();
    }

    public static FunctionUnlockConfig DeserializeFunctionUnlockConfig(ByteBuf _buf)
    {
        return new FunctionUnlockConfig(_buf);
    }

    public readonly FunctionUnlockType FunctionUnlockType;
    /// <summary>
    /// 条件组合
    /// </summary>
    public readonly string Condition;
   
    public const int __ID__ = 468304830;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "FunctionUnlockType:" + FunctionUnlockType + ","
        + "Condition:" + Condition + ","
        + "}";
    }
}
}

