
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Guide : Luban.BeanBase
{
    public Guide(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Next = _buf.ReadInt();
        Is3D = _buf.ReadBool();
        MaskType = _buf.ReadByte();
        ClickRange = _buf.ReadByte();
        Width = _buf.ReadInt();
        Height = _buf.ReadInt();
        Interactable = _buf.ReadBool();
        CanSkip = _buf.ReadByte();
    }

    public static Guide DeserializeGuide(ByteBuf _buf)
    {
        return new Guide(_buf);
    }

    public readonly int ID;
    public readonly int Next;
    public readonly bool Is3D;
    /// <summary>
    /// 0:无遮罩<br/>1:圆形<br/>2:矩形
    /// </summary>
    public readonly byte MaskType;
    /// <summary>
    /// 0:全屏<br/>1:mask范围内
    /// </summary>
    public readonly byte ClickRange;
    /// <summary>
    /// 矩形宽/圆形r
    /// </summary>
    public readonly int Width;
    /// <summary>
    /// 矩形高
    /// </summary>
    public readonly int Height;
    /// <summary>
    /// 穿透点击
    /// </summary>
    public readonly bool Interactable;
    /// <summary>
    /// 0:不可跳过<br/>1:调到下一步<br/>2:全部跳过
    /// </summary>
    public readonly byte CanSkip;
   
    public const int __ID__ = 69159644;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Next:" + Next + ","
        + "Is3D:" + Is3D + ","
        + "MaskType:" + MaskType + ","
        + "ClickRange:" + ClickRange + ","
        + "Width:" + Width + ","
        + "Height:" + Height + ","
        + "Interactable:" + Interactable + ","
        + "CanSkip:" + CanSkip + ","
        + "}";
    }
}

}

