
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Items : Luban.BeanBase
{
    public Items(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        ItemType = (ItemType)_buf.ReadInt();
        ItemNameKey = _buf.ReadString();
        ItemDesKey = _buf.ReadString();
        Icon = _buf.ReadString();
        Quality = (ItemQualityType)_buf.ReadInt();
        UseLevel = _buf.ReadInt();
        StackLimit = _buf.ReadInt();
        BindType = (ItemBindType)_buf.ReadInt();
        Price = _buf.ReadFloat();
        if(_buf.ReadBool()){ Attr = global::cfg.ItemAttr.DeserializeItemAttr(_buf); } else { Attr = null; }
    }

    public static Items DeserializeItems(ByteBuf _buf)
    {
        return new Items(_buf);
    }

    public readonly int ID;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly ItemType ItemType;
    /// <summary>
    /// 名字多语言
    /// </summary>
    public readonly string ItemNameKey;
    /// <summary>
    /// 描述多语言
    /// </summary>
    public readonly string ItemDesKey;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly ItemQualityType Quality;
    /// <summary>
    /// 使用等级限制
    /// </summary>
    public readonly int UseLevel;
    /// <summary>
    /// 背包堆叠上限
    /// </summary>
    public readonly int StackLimit;
    /// <summary>
    /// 绑定类型
    /// </summary>
    public readonly ItemBindType BindType;
    /// <summary>
    /// 价值
    /// </summary>
    public readonly float Price;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly ItemAttr Attr;
   
    public const int __ID__ = 70973344;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Attr?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ItemType:" + ItemType + ","
        + "ItemNameKey:" + ItemNameKey + ","
        + "ItemDesKey:" + ItemDesKey + ","
        + "Icon:" + Icon + ","
        + "Quality:" + Quality + ","
        + "UseLevel:" + UseLevel + ","
        + "StackLimit:" + StackLimit + ","
        + "BindType:" + BindType + ","
        + "Price:" + Price + ","
        + "Attr:" + Attr + ","
        + "}";
    }
}
}

