
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class LanguageEN : Luban.BeanBase
{
    public LanguageEN(ByteBuf _buf) 
    {
        Key = _buf.ReadInt();
        Value = _buf.ReadString();
    }

    public static LanguageEN DeserializeLanguageEN(ByteBuf _buf)
    {
        return new LanguageEN(_buf);
    }

    public readonly int Key;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Value;
   
    public const int __ID__ = 1816986145;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

