
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class PieceConfig : Luban.BeanBase
{
    public PieceConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Model = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Attrs = new System.Collections.Generic.Dictionary<int, float>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); float _v0;  _v0 = _buf.ReadFloat();     Attrs.Add(_k0, _v0);}}
        MoveMode = (MoveMode)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Skills = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Skills.Add(_e0);}}
    }

    public static PieceConfig DeserializePieceConfig(ByteBuf _buf)
    {
        return new PieceConfig(_buf);
    }

    public readonly int ID;
    public readonly string Model;
    /// <summary>
    /// 基础属性
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, float> Attrs;
    /// <summary>
    /// 移动类型
    /// </summary>
    public readonly MoveMode MoveMode;
    /// <summary>
    /// 拥有技能
    /// </summary>
    public readonly System.Collections.Generic.List<int> Skills;
   
    public const int __ID__ = -1138411600;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Model:" + Model + ","
        + "Attrs:" + Luban.StringUtil.CollectionToString(Attrs) + ","
        + "MoveMode:" + MoveMode + ","
        + "Skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
        + "}";
    }
}

}
