
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class PlayerAvatarPart : Luban.BeanBase
{
    public PlayerAvatarPart(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); OccupyPart = new System.Collections.Generic.List<PlayerAvatarPartType>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { PlayerAvatarPartType _e0;  _e0 = (PlayerAvatarPartType)_buf.ReadInt(); OccupyPart.Add(_e0);}}
        PrefabPath = _buf.ReadString();
    }

    public static PlayerAvatarPart DeserializePlayerAvatarPart(ByteBuf _buf)
    {
        return new PlayerAvatarPart(_buf);
    }

    public readonly int ID;
    public readonly System.Collections.Generic.List<PlayerAvatarPartType> OccupyPart;
    /// <summary>
    /// 资源名字
    /// </summary>
    public readonly string PrefabPath;
   
    public const int __ID__ = 1825807053;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "OccupyPart:" + Luban.StringUtil.CollectionToString(OccupyPart) + ","
        + "PrefabPath:" + PrefabPath + ","
        + "}";
    }
}
}

