//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
public sealed partial class PlayerAvatarPart :  Bright.Config.BeanBase 
{
    public PlayerAvatarPart(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);OccupyPart = new System.Collections.Generic.List<PlayerAvatarPartType>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { PlayerAvatarPartType _e0;  _e0 = (PlayerAvatarPartType)_buf.ReadInt(); OccupyPart.Add(_e0);}}
        PrefabName = _buf.ReadString();
        PostInit();
    }

    public static PlayerAvatarPart DeserializePlayerAvatarPart(ByteBuf _buf)
    {
        return new PlayerAvatarPart(_buf);
    }

    public int ID { get; private set; }
    public System.Collections.Generic.List<PlayerAvatarPartType> OccupyPart { get; private set; }
    /// <summary>
    /// 资源名字
    /// </summary>
    public string PrefabName { get; private set; }

    public const int __ID__ = 1825807053;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "OccupyPart:" + Bright.Common.StringUtil.CollectionToString(OccupyPart) + ","
        + "PrefabName:" + PrefabName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}