
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SimpleFightConfig : Luban.BeanBase
{
    public SimpleFightConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        FightConfig = FightConfig.DeserializeFightConfig(_buf);
    }

    public static SimpleFightConfig DeserializeSimpleFightConfig(ByteBuf _buf)
    {
        return new SimpleFightConfig(_buf);
    }

    public readonly int ID;
    /// <summary>
    /// 技能类型
    /// </summary>
    public readonly FightConfig FightConfig;
   
    public const int __ID__ = -1671766464;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "FightConfig:" + FightConfig + ","
        + "}";
    }
}

}

