
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SimplePieceConfig : Luban.BeanBase
{
    public SimplePieceConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        PieceConfig = PieceConfig.DeserializePieceConfig(_buf);
    }

    public static SimplePieceConfig DeserializeSimplePieceConfig(ByteBuf _buf)
    {
        return new SimplePieceConfig(_buf);
    }

    public readonly int ID;
    /// <summary>
    /// 技能类型
    /// </summary>
    public readonly PieceConfig PieceConfig;
   
    public const int __ID__ = 601727646;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "PieceConfig:" + PieceConfig + ","
        + "}";
    }
}

}

