
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbActionConfig : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, ActionConfig> _dataMap = new System.Collections.Generic.Dictionary<int, ActionConfig>();
    private readonly System.Collections.Generic.List<ActionConfig> _dataList = new System.Collections.Generic.List<ActionConfig>();
    
    public void Deserialize(byte[] bytes)
    {
        _dataMap.Clear();
        _dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        int n = _buf.ReadSize();
        for(int i = n ; i > 0 ; --i)
        {
            ActionConfig _v;
            _v = global::cfg.ActionConfig.DeserializeActionConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ActionConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ActionConfig> DataList => _dataList;

    public ActionConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ActionConfig Get(int key) => _dataMap[key];
    public ActionConfig this[int key] => _dataMap[key];


}

}

