
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbActivityConfig : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, ActivityConfig> _dataMap = new System.Collections.Generic.Dictionary<int, ActivityConfig>();
    private readonly System.Collections.Generic.List<ActivityConfig> _dataList = new System.Collections.Generic.List<ActivityConfig>();
    
    public void Deserialize(byte[] bytes)
    {
        _dataMap.Clear();
        _dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        int n = _buf.ReadSize();
        for(int i = n ; i > 0 ; --i)
        {
            ActivityConfig _v;
            _v = global::cfg.ActivityConfig.DeserializeActivityConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ActivityConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ActivityConfig> DataList => _dataList;

    public ActivityConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ActivityConfig Get(int key) => _dataMap[key];
    public ActivityConfig this[int key] => _dataMap[key];


}

}

