
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbActionConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ActionConfig> _dataMap;
    private readonly System.Collections.Generic.List<ActionConfig> _dataList;
    
    public TbActionConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ActionConfig>(n);
        _dataList = new System.Collections.Generic.List<ActionConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ActionConfig _v;
            _v = global::cfg.ActionConfig.DeserializeActionConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ActionConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ActionConfig> DataList => _dataList;

    public ActionConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ActionConfig Get(int key) => _dataMap[key];
    public ActionConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

