
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbConstConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ConstConfig> _dataMap;
    private readonly System.Collections.Generic.List<ConstConfig> _dataList;
    
    public TbConstConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ConstConfig>(n);
        _dataList = new System.Collections.Generic.List<ConstConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ConstConfig _v;
            _v = global::cfg.ConstConfig.DeserializeConstConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ConstConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ConstConfig> DataList => _dataList;

    public ConstConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ConstConfig Get(int key) => _dataMap[key];
    public ConstConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

