
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbDamageNumConfig : TbBase
{
    private readonly System.Collections.Generic.Dictionary<DamageNumType, DamageNumConfig> _dataMap = new System.Collections.Generic.Dictionary<DamageNumType, DamageNumConfig>();
    private readonly System.Collections.Generic.List<DamageNumConfig> _dataList = new System.Collections.Generic.List<DamageNumConfig>();
    
    public void Deserialize(byte[] bytes)
    {
        _dataMap.Clear();
        _dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        int n = _buf.ReadSize();
        for(int i = n ; i > 0 ; --i)
        {
            DamageNumConfig _v;
            _v = global::cfg.DamageNumConfig.DeserializeDamageNumConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.DamageNumType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<DamageNumType, DamageNumConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<DamageNumConfig> DataList => _dataList;

    public DamageNumConfig GetOrDefault(DamageNumType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DamageNumConfig Get(DamageNumType key) => _dataMap[key];
    public DamageNumConfig this[DamageNumType key] => _dataMap[key];


}

}

