
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbFunctionUnlockConfig : TbBase
{
    private readonly System.Collections.Generic.Dictionary<FunctionUnlockType, FunctionUnlockConfig> _dataMap = new System.Collections.Generic.Dictionary<FunctionUnlockType, FunctionUnlockConfig>();
    private readonly System.Collections.Generic.List<FunctionUnlockConfig> _dataList = new System.Collections.Generic.List<FunctionUnlockConfig>();
    
    public void Deserialize(byte[] bytes)
    {
        _dataMap.Clear();
        _dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        int n = _buf.ReadSize();
        for(int i = n ; i > 0 ; --i)
        {
            FunctionUnlockConfig _v;
            _v = global::cfg.FunctionUnlockConfig.DeserializeFunctionUnlockConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.FunctionUnlockType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<FunctionUnlockType, FunctionUnlockConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<FunctionUnlockConfig> DataList => _dataList;

    public FunctionUnlockConfig GetOrDefault(FunctionUnlockType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FunctionUnlockConfig Get(FunctionUnlockType key) => _dataMap[key];
    public FunctionUnlockConfig this[FunctionUnlockType key] => _dataMap[key];


}

}

