
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbItems : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, Items> _dataMap = new System.Collections.Generic.Dictionary<int, Items>();
    private readonly System.Collections.Generic.List<Items> _dataList = new System.Collections.Generic.List<Items>();
    
    public void Deserialize(byte[] bytes)
    {
        _dataMap.Clear();
        _dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        int n = _buf.ReadSize();
        for(int i = n ; i > 0 ; --i)
        {
            Items _v;
            _v = global::cfg.Items.DeserializeItems(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Items> DataMap => _dataMap;
    public System.Collections.Generic.List<Items> DataList => _dataList;

    public Items GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Items Get(int key) => _dataMap[key];
    public Items this[int key] => _dataMap[key];


}

}

