
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbLanguageEN
{
    private readonly System.Collections.Generic.Dictionary<int, LanguageEN> _dataMap;
    private readonly System.Collections.Generic.List<LanguageEN> _dataList;
    
    public TbLanguageEN(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, LanguageEN>(n);
        _dataList = new System.Collections.Generic.List<LanguageEN>(n);
        for(int i = n ; i > 0 ; --i)
        {
            LanguageEN _v;
            _v = global::cfg.LanguageEN.DeserializeLanguageEN(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LanguageEN> DataMap => _dataMap;
    public System.Collections.Generic.List<LanguageEN> DataList => _dataList;

    public LanguageEN GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LanguageEN Get(int key) => _dataMap[key];
    public LanguageEN this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

