//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
   
public partial class TbPlayerAvatarPart : TbBase
{
    private readonly Dictionary<int, PlayerAvatarPart> _dataMap = new Dictionary<int, PlayerAvatarPart>();
    private readonly List<PlayerAvatarPart> _dataList = new List<PlayerAvatarPart>();
    
    public void Deserialize(byte[] bytes)
    {
		_dataMap.Clear();
		_dataList.Clear();
		ByteBuf _buf = new ByteBuf(bytes);
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            PlayerAvatarPart _v;
            _v = PlayerAvatarPart.DeserializePlayerAvatarPart(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, PlayerAvatarPart> DataMap => _dataMap;
    public List<PlayerAvatarPart> DataList => _dataList;

    public PlayerAvatarPart GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PlayerAvatarPart Get(int key) => _dataMap[key];
    public PlayerAvatarPart this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}