
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbTriggerCondition : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, TriggerCondition> _dataMap = new System.Collections.Generic.Dictionary<int, TriggerCondition>();
    private readonly System.Collections.Generic.List<TriggerCondition> _dataList = new System.Collections.Generic.List<TriggerCondition>();
    
    public void Deserialize(byte[] bytes)
    {
		_dataMap.Clear();
		_dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TriggerCondition _v;
            _v = TriggerCondition.DeserializeTriggerCondition(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TriggerCondition> DataMap => _dataMap;
    public System.Collections.Generic.List<TriggerCondition> DataList => _dataList;

    public TriggerCondition GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TriggerCondition Get(int key) => _dataMap[key];
    public TriggerCondition this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
