
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbTriggerAction : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, TriggerAction> _dataMap = new System.Collections.Generic.Dictionary<int, TriggerAction>();
    private readonly System.Collections.Generic.List<TriggerAction> _dataList = new System.Collections.Generic.List<TriggerAction>();
    
    public void Deserialize(byte[] bytes)
    {
		_dataMap.Clear();
		_dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TriggerAction _v;
            _v = TriggerAction.DeserializeTriggerAction(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TriggerAction> DataMap => _dataMap;
    public System.Collections.Generic.List<TriggerAction> DataList => _dataList;

    public TriggerAction GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TriggerAction Get(int key) => _dataMap[key];
    public TriggerAction this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
