
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbTrigger
{
    private readonly System.Collections.Generic.Dictionary<int, Trigger> _dataMap;
    private readonly System.Collections.Generic.List<Trigger> _dataList;
    
    public TbTrigger(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Trigger>(n);
        _dataList = new System.Collections.Generic.List<Trigger>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Trigger _v;
            _v = global::cfg.Trigger.DeserializeTrigger(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Trigger> DataMap => _dataMap;
    public System.Collections.Generic.List<Trigger> DataList => _dataList;

    public Trigger GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Trigger Get(int key) => _dataMap[key];
    public Trigger this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

