
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbUIConfig
{
    private readonly System.Collections.Generic.Dictionary<UIType, UIConfig> _dataMap;
    private readonly System.Collections.Generic.List<UIConfig> _dataList;
    
    public TbUIConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<UIType, UIConfig>();
        _dataList = new System.Collections.Generic.List<UIConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UIConfig _v;
            _v = UIConfig.DeserializeUIConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.UIType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<UIType, UIConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<UIConfig> DataList => _dataList;

    public UIConfig GetOrDefault(UIType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UIConfig Get(UIType key) => _dataMap[key];
    public UIConfig this[UIType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
