//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
   
public partial class TbUIConfig : TbBase
{
    private readonly Dictionary<UIType, UIConfig> _dataMap = new();
    private readonly List<UIConfig> _dataList = new();
    
    public void Deserialize(byte[] bytes)
    {
		_dataMap.Clear();
		_dataList.Clear();
		ByteBuf _buf = new(bytes);
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UIConfig _v;
            _v = UIConfig.DeserializeUIConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.UIType, _v);
        }
        PostInit();
    }

    public Dictionary<UIType, UIConfig> DataMap => _dataMap;
    public List<UIConfig> DataList => _dataList;

    public UIConfig GetOrDefault(UIType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UIConfig Get(UIType key) => _dataMap[key];
    public UIConfig this[UIType key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}