
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum TriggerMode
    {
        Attack = 1,
        BeDamage = 2,
        AddBuff = 3,
        RemoveBuff = 4,
        ExcuteBuff = 5,
        PropChange = 6,
    }

} 

