
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TriggerCondition : Luban.BeanBase
{
    public TriggerCondition(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        TriggerType = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Param = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); Param.Add(_e0);}}
    }

    public static TriggerCondition DeserializeTriggerCondition(ByteBuf _buf)
    {
        return new TriggerCondition(_buf);
    }

    public readonly int ID;
    /// <summary>
    /// 触发器类型
    /// </summary>
    public readonly string TriggerType;
    /// <summary>
    /// 触发条件参数
    /// </summary>
    public readonly System.Collections.Generic.List<float> Param;
   
    public const int __ID__ = -2050659741;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "TriggerType:" + TriggerType + ","
        + "Param:" + Luban.StringUtil.CollectionToString(Param) + ","
        + "}";
    }
}

}
