
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum UIType
    {
        UITest = 1,
        UICommonBox = 2,
        UIHotUpdateRes = 3,
        UIMain = 4,
        UISetting = 5,
        UICommonTips = 6,
        UISceneLoading = 7,
        UIGuide = 8,
        UIMail = 9,
    }

} 

