// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Mail.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Message
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CSMail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MailDetail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint mailId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public MailType Type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        public uint Status { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"time")]
        public long Time { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"title")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Title { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"rewards")]
        public global::System.Collections.Generic.List<RewardInfo> Rewards { get; } = new global::System.Collections.Generic.List<RewardInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SCMail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"details")]
        public global::System.Collections.Generic.List<MailDetail> Details { get; } = new global::System.Collections.Generic.List<MailDetail>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum MailType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SYSTEM")]
        System = 0,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
