
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ActionConfig : Luban.BeanBase
{
    public ActionConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        ActionType = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IntParam = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); IntParam.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);FloatParam = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); FloatParam.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);StrParam = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); StrParam.Add(_e0);}}
    }

    public static ActionConfig DeserializeActionConfig(ByteBuf _buf)
    {
        return new ActionConfig(_buf);
    }

    public readonly int ID;
    /// <summary>
    /// 触发器类型
    /// </summary>
    public readonly string ActionType;
    /// <summary>
    /// 触发条件参数
    /// </summary>
    public readonly System.Collections.Generic.List<int> IntParam;
    /// <summary>
    /// 触发条件参数
    /// </summary>
    public readonly System.Collections.Generic.List<float> FloatParam;
    /// <summary>
    /// 触发条件参数
    /// </summary>
    public readonly System.Collections.Generic.List<string> StrParam;
   
    public const int __ID__ = 1209614648;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ActionType:" + ActionType + ","
        + "IntParam:" + Luban.StringUtil.CollectionToString(IntParam) + ","
        + "FloatParam:" + Luban.StringUtil.CollectionToString(FloatParam) + ","
        + "StrParam:" + Luban.StringUtil.CollectionToString(StrParam) + ","
        + "}";
    }
}

}
