
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class BattleConst : Luban.BeanBase
{
    public BattleConst(ByteBuf _buf) 
    {
        BrushInterval = _buf.ReadFloat();
    }

    public static BattleConst DeserializeBattleConst(ByteBuf _buf)
    {
        return new BattleConst(_buf);
    }

    public readonly float BrushInterval;
   
    public const int __ID__ = 892555627;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "BrushInterval:" + BrushInterval + ","
        + "}";
    }
}

}

