
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class BuffCondition : Luban.BeanBase
{
    public BuffCondition(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        BuffType = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Param = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); Param.Add(_e0);}}
    }

    public static BuffCondition DeserializeBuffCondition(ByteBuf _buf)
    {
        return new BuffCondition(_buf);
    }

    /// <summary>
    /// 条件组合()!&amp;|0 <br/>最外层必须为括号<br/>非括号内的执行优先级从后往前
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 触发器类型
    /// </summary>
    public readonly string BuffType;
    /// <summary>
    /// 触发条件参数
    /// </summary>
    public readonly System.Collections.Generic.List<float> Param;
   
    public const int __ID__ = -294250008;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "BuffType:" + BuffType + ","
        + "Param:" + Luban.StringUtil.CollectionToString(Param) + ","
        + "}";
    }
}

}
