//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
public sealed partial class DeviceInfo :  Bright.Config.BeanBase 
{
    public DeviceInfo(ByteBuf _buf) 
    {
        Name = _buf.ReadString();
        Lv = _buf.ReadInt();
        SupportES3 = _buf.ReadBool();
        PostInit();
    }

    public static DeviceInfo DeserializeDeviceInfo(ByteBuf _buf)
    {
        return new DeviceInfo(_buf);
    }

    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 设备分级
    /// </summary>
    public int Lv { get; private set; }
    /// <summary>
    /// 是否支持opgngles3
    /// </summary>
    public bool SupportES3 { get; private set; }

    public const int __ID__ = -1520650172;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Lv:" + Lv + ","
        + "SupportES3:" + SupportES3 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}