
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class EquipItemAttr : ItemAttr
{
    public EquipItemAttr(ByteBuf _buf)  : base(_buf) 
    {
        Hp = _buf.ReadInt();
        Attack = _buf.ReadInt();
    }

    public static EquipItemAttr DeserializeEquipItemAttr(ByteBuf _buf)
    {
        return new EquipItemAttr(_buf);
    }

    public readonly int Hp;
    public readonly int Attack;
   
    public const int __ID__ = 357684180;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Hp:" + Hp + ","
        + "Attack:" + Attack + ","
        + "}";
    }
}
}

