
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ItemQualityType
    {
        White = 1,
        Green = 2,
        Blue = 3,
        Purple = 4,
        Orange = 5,
        Gold = 6,
    }

} 

