
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ItemBindType
    {
        None = 1,
        BindOnPickup = 2,
        BindOnEquip = 3,
        BindOnUse = 4,
    }

} 

