
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public abstract partial class ItemAttr : Luban.BeanBase
{
    public ItemAttr(ByteBuf _buf) 
    {
    }

    public static ItemAttr DeserializeItemAttr(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case EquipItemAttr.__ID__: return new EquipItemAttr(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

