
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Link : Luban.BeanBase
{
    public Link(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
    }

    public static Link DeserializeLink(ByteBuf _buf)
    {
        return new Link(_buf);
    }

    public readonly int ID;
   
    public const int __ID__ = 2368538;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "}";
    }
}
}

