
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class MonsterConfig : Luban.BeanBase
{
    public MonsterConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        FightConfig = global::cfg.FightConfig.DeserializeFightConfig(_buf);
        MonsterType = (MonsterType)_buf.ReadInt();
    }

    public static MonsterConfig DeserializeMonsterConfig(ByteBuf _buf)
    {
        return new MonsterConfig(_buf);
    }

    public readonly int ID;
    public readonly FightConfig FightConfig;
    public readonly MonsterType MonsterType;
   
    public const int __ID__ = -55174244;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "FightConfig:" + FightConfig + ","
        + "MonsterType:" + MonsterType + ","
        + "}";
    }
}
}

