
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SceneConfig : Luban.BeanBase
{
    public SceneConfig(ByteBuf _buf) 
    {
        SceneType = (SceneType)_buf.ReadInt();
        Name = _buf.ReadString();
        PrefabPath = _buf.ReadString();
        SkyBoxPath = _buf.ReadString();
        CameraPos = ExternalTypeUtil.NewVector3(global::cfg.vec3.Deserializevec3(_buf));
        CameraEuler = ExternalTypeUtil.NewVector3(global::cfg.vec3.Deserializevec3(_buf));
    }

    public static SceneConfig DeserializeSceneConfig(ByteBuf _buf)
    {
        return new SceneConfig(_buf);
    }

    public readonly SceneType SceneType;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 资源名字
    /// </summary>
    public readonly string PrefabPath;
    /// <summary>
    /// 天空盒
    /// </summary>
    public readonly string SkyBoxPath;
    /// <summary>
    /// 相机位置
    /// </summary>
    public readonly UnityEngine.Vector3 CameraPos;
    /// <summary>
    /// 相机位置
    /// </summary>
    public readonly UnityEngine.Vector3 CameraEuler;
   
    public const int __ID__ = 935827150;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "SceneType:" + SceneType + ","
        + "Name:" + Name + ","
        + "PrefabPath:" + PrefabPath + ","
        + "SkyBoxPath:" + SkyBoxPath + ","
        + "CameraPos:" + CameraPos + ","
        + "CameraEuler:" + CameraEuler + ","
        + "}";
    }
}
}

