
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SceneConfig : Luban.BeanBase
{
    public SceneConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        SceneType = (SceneType)_buf.ReadInt();
        Ame = _buf.ReadString();
        PrefabName = _buf.ReadString();
    }

    public static SceneConfig DeserializeSceneConfig(ByteBuf _buf)
    {
        return new SceneConfig(_buf);
    }

    public readonly int ID;
    public readonly SceneType SceneType;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Ame;
    /// <summary>
    /// 资源名字
    /// </summary>
    public readonly string PrefabName;
   
    public const int __ID__ = 935827150;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "SceneType:" + SceneType + ","
        + "ame:" + Ame + ","
        + "PrefabName:" + PrefabName + ","
        + "}";
    }
}

}
