
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SkillConfig : Luban.BeanBase
{
    public SkillConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        NeedTarget = _buf.ReadBool();
        Cooldown = _buf.ReadFloat();
        Interval = _buf.ReadFloat();
        Delay = _buf.ReadFloat();
        AtkDis = _buf.ReadFloat();
        InterruptPriority = _buf.ReadInt();
        BeInterruptPriority = _buf.ReadInt();
    }

    public static SkillConfig DeserializeSkillConfig(ByteBuf _buf)
    {
        return new SkillConfig(_buf);
    }

    public readonly int ID;
    /// <summary>
    /// 需要目标
    /// </summary>
    public readonly bool NeedTarget;
    /// <summary>
    /// 冷却时间
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public readonly float Interval;
    /// <summary>
    /// 前摇
    /// </summary>
    public readonly float Delay;
    /// <summary>
    /// 攻击距离
    /// </summary>
    public readonly float AtkDis;
    /// <summary>
    /// 打断优先级
    /// </summary>
    public readonly int InterruptPriority;
    /// <summary>
    /// 被打断优先级
    /// </summary>
    public readonly int BeInterruptPriority;
   
    public const int __ID__ = -844226349;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "NeedTarget:" + NeedTarget + ","
        + "Cooldown:" + Cooldown + ","
        + "Interval:" + Interval + ","
        + "Delay:" + Delay + ","
        + "AtkDis:" + AtkDis + ","
        + "InterruptPriority:" + InterruptPriority + ","
        + "BeInterruptPriority:" + BeInterruptPriority + ","
        + "}";
    }
}

}
