
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SkillConfig : Luban.BeanBase
{
    public SkillConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        FightConfig = global::cfg.FightConfig.DeserializeFightConfig(_buf);
        SkillType = (SkillType)_buf.ReadInt();
        NeedTarget = _buf.ReadBool();
        Cooldown = _buf.ReadFloat();
        Anticipation = _buf.ReadFloat();
        AtkDis = _buf.ReadFloat();
        InterruptPriority = _buf.ReadInt();
        BeInterruptPriority = _buf.ReadInt();
        ColliderType = (DamageRangeType)_buf.ReadInt();
        ColliderWidth = _buf.ReadFloat();
        ColliderHeight = _buf.ReadFloat();
        Delay = _buf.ReadFloat();
        Duration = _buf.ReadFloat();
        Internal = _buf.ReadFloat();
    }

    public static SkillConfig DeserializeSkillConfig(ByteBuf _buf)
    {
        return new SkillConfig(_buf);
    }

    public readonly int ID;
    /// <summary>
    /// 技能类型
    /// </summary>
    public readonly FightConfig FightConfig;
    /// <summary>
    /// 技能类型
    /// </summary>
    public readonly SkillType SkillType;
    /// <summary>
    /// 需要目标
    /// </summary>
    public readonly bool NeedTarget;
    /// <summary>
    /// 冷却时间
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 前摇
    /// </summary>
    public readonly float Anticipation;
    /// <summary>
    /// 攻击距离
    /// </summary>
    public readonly float AtkDis;
    /// <summary>
    /// 打断优先级
    /// </summary>
    public readonly int InterruptPriority;
    /// <summary>
    /// 被打断优先级
    /// </summary>
    public readonly int BeInterruptPriority;
    /// <summary>
    /// 伤害范围
    /// </summary>
    public readonly DamageRangeType ColliderType;
    /// <summary>
    /// 宽/半径
    /// </summary>
    public readonly float ColliderWidth;
    /// <summary>
    /// 高
    /// </summary>
    public readonly float ColliderHeight;
    /// <summary>
    /// 延迟时间(配合动画)
    /// </summary>
    public readonly float Delay;
    /// <summary>
    /// 持续时间(0:伤害一次)
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 伤害间隔
    /// </summary>
    public readonly float Internal;
   
    public const int __ID__ = -844226349;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "FightConfig:" + FightConfig + ","
        + "SkillType:" + SkillType + ","
        + "NeedTarget:" + NeedTarget + ","
        + "Cooldown:" + Cooldown + ","
        + "Anticipation:" + Anticipation + ","
        + "AtkDis:" + AtkDis + ","
        + "InterruptPriority:" + InterruptPriority + ","
        + "BeInterruptPriority:" + BeInterruptPriority + ","
        + "ColliderType:" + ColliderType + ","
        + "ColliderWidth:" + ColliderWidth + ","
        + "ColliderHeight:" + ColliderHeight + ","
        + "Delay:" + Delay + ","
        + "Duration:" + Duration + ","
        + "Internal:" + Internal + ","
        + "}";
    }
}
}

