//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;



namespace cfg
{ 
public partial class Tables
{
    public TbUIConfig TbUIConfig = new TbUIConfig();
    public TbDeviceInfo TbDeviceInfo = new TbDeviceInfo();
    public TbSceneConfig TbSceneConfig = new TbSceneConfig();
    public TbPlayerAvatarPart TbPlayerAvatarPart = new TbPlayerAvatarPart();
}

}