
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public abstract partial class TbBuffBase : Luban.BeanBase
{
    public TbBuffBase(ByteBuf _buf) 
    {
        Priority = _buf.ReadInt();
        Limit = _buf.ReadInt();
        TotalTime = _buf.ReadFloat();
        Condition = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Action = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Action.Add(_e0);}}
    }

    public static TbBuffBase DeserializeTbBuffBase(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case TbBuff_Normal.__ID__: return new TbBuff_Normal(_buf);
            case TbBuff_Count.__ID__: return new TbBuff_Count(_buf);
            case TbBuff_Internal.__ID__: return new TbBuff_Internal(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int Priority;
    public readonly int Limit;
    public readonly float TotalTime;
    public readonly string Condition;
    public readonly System.Collections.Generic.List<int> Action;
   

    public virtual void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Priority:" + Priority + ","
        + "Limit:" + Limit + ","
        + "TotalTime:" + TotalTime + ","
        + "Condition:" + Condition + ","
        + "Action:" + Luban.StringUtil.CollectionToString(Action) + ","
        + "}";
    }
}

}
