
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TbBuff_Normal : TbBuffBase
{
    public TbBuff_Normal(ByteBuf _buf)  : base(_buf) 
    {
    }

    public static TbBuff_Normal DeserializeTbBuff_Normal(ByteBuf _buf)
    {
        return new TbBuff_Normal(_buf);
    }

   
    public const int __ID__ = -513934587;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Priority:" + Priority + ","
        + "Limit:" + Limit + ","
        + "TotalTime:" + TotalTime + ","
        + "Condition:" + Condition + ","
        + "Action:" + Luban.StringUtil.CollectionToString(Action) + ","
        + "}";
    }
}

}
