
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TbBuff_Internal : TbBuffBase
{
    public TbBuff_Internal(ByteBuf _buf)  : base(_buf) 
    {
        CDTime = _buf.ReadFloat();
    }

    public static TbBuff_Internal DeserializeTbBuff_Internal(ByteBuf _buf)
    {
        return new TbBuff_Internal(_buf);
    }

    /// <summary>
    /// 冷却时间
    /// </summary>
    public readonly float CDTime;
   
    public const int __ID__ = -931138213;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        
    }

    public override string ToString()
    {
        return "{ "
        + "Priority:" + Priority + ","
        + "Limit:" + Limit + ","
        + "TotalTime:" + TotalTime + ","
        + "Condition:" + Condition + ","
        + "Action:" + Luban.StringUtil.CollectionToString(Action) + ","
        + "CDTime:" + CDTime + ","
        + "}";
    }
}

}
