
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbBuffAction : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, BuffAction> _dataMap = new System.Collections.Generic.Dictionary<int, BuffAction>();
    private readonly System.Collections.Generic.List<BuffAction> _dataList = new System.Collections.Generic.List<BuffAction>();
    
    public void Deserialize(byte[] bytes)
    {
		_dataMap.Clear();
		_dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            BuffAction _v;
            _v = BuffAction.DeserializeBuffAction(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BuffAction> DataMap => _dataMap;
    public System.Collections.Generic.List<BuffAction> DataList => _dataList;

    public BuffAction GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BuffAction Get(int key) => _dataMap[key];
    public BuffAction this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
