
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbConditionConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ConditionConfig> _dataMap;
    private readonly System.Collections.Generic.List<ConditionConfig> _dataList;
    
    public TbConditionConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ConditionConfig>(n);
        _dataList = new System.Collections.Generic.List<ConditionConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ConditionConfig _v;
            _v = global::cfg.ConditionConfig.DeserializeConditionConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ConditionConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ConditionConfig> DataList => _dataList;

    public ConditionConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ConditionConfig Get(int key) => _dataMap[key];
    public ConditionConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

