
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbConditionConfig : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, ConditionConfig> _dataMap = new System.Collections.Generic.Dictionary<int, ConditionConfig>();
    private readonly System.Collections.Generic.List<ConditionConfig> _dataList = new System.Collections.Generic.List<ConditionConfig>();
    
    public void Deserialize(byte[] bytes)
    {
		_dataMap.Clear();
		_dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ConditionConfig _v;
            _v = ConditionConfig.DeserializeConditionConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ConditionConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ConditionConfig> DataList => _dataList;

    public ConditionConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ConditionConfig Get(int key) => _dataMap[key];
    public ConditionConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
