//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
   
public partial class TbDeviceInfo : TbBase
{
    private readonly Dictionary<string, DeviceInfo> _dataMap = new Dictionary<string, DeviceInfo>();
    private readonly List<DeviceInfo> _dataList = new List<DeviceInfo>();
    
    public void Deserialize(byte[] bytes)
    {
		_dataMap.Clear();
		_dataList.Clear();
		ByteBuf _buf = new ByteBuf(bytes);
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DeviceInfo _v;
            _v = DeviceInfo.DeserializeDeviceInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
        }
        PostInit();
    }

    public Dictionary<string, DeviceInfo> DataMap => _dataMap;
    public List<DeviceInfo> DataList => _dataList;

    public DeviceInfo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DeviceInfo Get(string key) => _dataMap[key];
    public DeviceInfo this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}