
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbDeviceInfo
{
    private readonly System.Collections.Generic.Dictionary<string, DeviceInfo> _dataMap;
    private readonly System.Collections.Generic.List<DeviceInfo> _dataList;
    
    public TbDeviceInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, DeviceInfo>(n);
        _dataList = new System.Collections.Generic.List<DeviceInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DeviceInfo _v;
            _v = global::cfg.DeviceInfo.DeserializeDeviceInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, DeviceInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<DeviceInfo> DataList => _dataList;

    public DeviceInfo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DeviceInfo Get(string key) => _dataMap[key];
    public DeviceInfo this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

