
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbFunctionUnlockConfig
{
    private readonly System.Collections.Generic.Dictionary<FunctionUnlockType, FunctionUnlockConfig> _dataMap;
    private readonly System.Collections.Generic.List<FunctionUnlockConfig> _dataList;
    
    public TbFunctionUnlockConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<FunctionUnlockType, FunctionUnlockConfig>(n);
        _dataList = new System.Collections.Generic.List<FunctionUnlockConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            FunctionUnlockConfig _v;
            _v = global::cfg.FunctionUnlockConfig.DeserializeFunctionUnlockConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.FunctionUnlockType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<FunctionUnlockType, FunctionUnlockConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<FunctionUnlockConfig> DataList => _dataList;

    public FunctionUnlockConfig GetOrDefault(FunctionUnlockType key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public FunctionUnlockConfig Get(FunctionUnlockType key) => _dataMap[key];
    public FunctionUnlockConfig this[FunctionUnlockType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

