
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbGuide : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, Guide> _dataMap = new System.Collections.Generic.Dictionary<int, Guide>();
    private readonly System.Collections.Generic.List<Guide> _dataList = new System.Collections.Generic.List<Guide>();
    
    public void Deserialize(byte[] bytes)
    {
        _dataMap.Clear();
        _dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        int n = _buf.ReadSize();
        for(int i = n ; i > 0 ; --i)
        {
            Guide _v;
            _v = global::cfg.Guide.DeserializeGuide(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Guide> DataMap => _dataMap;
    public System.Collections.Generic.List<Guide> DataList => _dataList;

    public Guide GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Guide Get(int key) => _dataMap[key];
    public Guide this[int key] => _dataMap[key];


}

}

