
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbLanguageCN : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, LanguageCN> _dataMap = new System.Collections.Generic.Dictionary<int, LanguageCN>();
    private readonly System.Collections.Generic.List<LanguageCN> _dataList = new System.Collections.Generic.List<LanguageCN>();
    
    public void Deserialize(byte[] bytes)
    {
        _dataMap.Clear();
        _dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        int n = _buf.ReadSize();
        for(int i = n ; i > 0 ; --i)
        {
            LanguageCN _v;
            _v = global::cfg.LanguageCN.DeserializeLanguageCN(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LanguageCN> DataMap => _dataMap;
    public System.Collections.Generic.List<LanguageCN> DataList => _dataList;

    public LanguageCN GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LanguageCN Get(int key) => _dataMap[key];
    public LanguageCN this[int key] => _dataMap[key];


}

}

