
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbLanguageCN
{
    private readonly System.Collections.Generic.Dictionary<int, LanguageCN> _dataMap;
    private readonly System.Collections.Generic.List<LanguageCN> _dataList;
    
    public TbLanguageCN(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, LanguageCN>(n);
        _dataList = new System.Collections.Generic.List<LanguageCN>(n);
        for(int i = n ; i > 0 ; --i)
        {
            LanguageCN _v;
            _v = global::cfg.LanguageCN.DeserializeLanguageCN(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LanguageCN> DataMap => _dataMap;
    public System.Collections.Generic.List<LanguageCN> DataList => _dataList;

    public LanguageCN GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LanguageCN Get(int key) => _dataMap[key];
    public LanguageCN this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

