
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbLink : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, Link> _dataMap = new System.Collections.Generic.Dictionary<int, Link>();
    private readonly System.Collections.Generic.List<Link> _dataList = new System.Collections.Generic.List<Link>();
    
    public void Deserialize(byte[] bytes)
    {
        _dataMap.Clear();
        _dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        int n = _buf.ReadSize();
        for(int i = n ; i > 0 ; --i)
        {
            Link _v;
            _v = global::cfg.Link.DeserializeLink(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Link> DataMap => _dataMap;
    public System.Collections.Generic.List<Link> DataList => _dataList;

    public Link GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Link Get(int key) => _dataMap[key];
    public Link this[int key] => _dataMap[key];


}

}

