
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbLink
{
    private readonly System.Collections.Generic.Dictionary<int, Link> _dataMap;
    private readonly System.Collections.Generic.List<Link> _dataList;
    
    public TbLink(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Link>(n);
        _dataList = new System.Collections.Generic.List<Link>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Link _v;
            _v = global::cfg.Link.DeserializeLink(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Link> DataMap => _dataMap;
    public System.Collections.Generic.List<Link> DataList => _dataList;

    public Link GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Link Get(int key) => _dataMap[key];
    public Link this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

