
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbMonsterConfig : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, MonsterConfig> _dataMap = new System.Collections.Generic.Dictionary<int, MonsterConfig>();
    private readonly System.Collections.Generic.List<MonsterConfig> _dataList = new System.Collections.Generic.List<MonsterConfig>();
    
    public void Deserialize(byte[] bytes)
    {
        _dataMap.Clear();
        _dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        int n = _buf.ReadSize();
        for(int i = n ; i > 0 ; --i)
        {
            MonsterConfig _v;
            _v = global::cfg.MonsterConfig.DeserializeMonsterConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MonsterConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<MonsterConfig> DataList => _dataList;

    public MonsterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MonsterConfig Get(int key) => _dataMap[key];
    public MonsterConfig this[int key] => _dataMap[key];


}

}

