
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbPieceConfig : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, PieceConfig> _dataMap = new System.Collections.Generic.Dictionary<int, PieceConfig>();
    private readonly System.Collections.Generic.List<PieceConfig> _dataList = new System.Collections.Generic.List<PieceConfig>();
    
    public void Deserialize(byte[] bytes)
    {
		_dataMap.Clear();
		_dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            PieceConfig _v;
            _v = PieceConfig.DeserializePieceConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PieceConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<PieceConfig> DataList => _dataList;

    public PieceConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PieceConfig Get(int key) => _dataMap[key];
    public PieceConfig this[int key] => _dataMap[key];


}

}

