
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbSceneConfig : TbBase
{
    private readonly System.Collections.Generic.Dictionary<SceneType, SceneConfig> _dataMap = new System.Collections.Generic.Dictionary<SceneType, SceneConfig>();
    private readonly System.Collections.Generic.List<SceneConfig> _dataList = new System.Collections.Generic.List<SceneConfig>();
    
    public void Deserialize(byte[] bytes)
    {
		_dataMap.Clear();
		_dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SceneConfig _v;
            _v = SceneConfig.DeserializeSceneConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.SceneType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<SceneType, SceneConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SceneConfig> DataList => _dataList;

    public SceneConfig GetOrDefault(SceneType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SceneConfig Get(SceneType key) => _dataMap[key];
    public SceneConfig this[SceneType key] => _dataMap[key];


}

}

