//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
   
public partial class TbSceneConfig : TbBase
{
    private Dictionary<int, SceneConfig> _dataMap;
    private List<SceneConfig> _dataList;
    
    public void Deserialize(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, SceneConfig>();
        _dataList = new List<SceneConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SceneConfig _v;
            _v = SceneConfig.DeserializeSceneConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, SceneConfig> DataMap => _dataMap;
    public List<SceneConfig> DataList => _dataList;

    public SceneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SceneConfig Get(int key) => _dataMap[key];
    public SceneConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}