
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbSimplePieceConfig : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, SimplePieceConfig> _dataMap = new System.Collections.Generic.Dictionary<int, SimplePieceConfig>();
    private readonly System.Collections.Generic.List<SimplePieceConfig> _dataList = new System.Collections.Generic.List<SimplePieceConfig>();
    
    public void Deserialize(byte[] bytes)
    {
		_dataMap.Clear();
		_dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SimplePieceConfig _v;
            _v = SimplePieceConfig.DeserializeSimplePieceConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SimplePieceConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SimplePieceConfig> DataList => _dataList;

    public SimplePieceConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SimplePieceConfig Get(int key) => _dataMap[key];
    public SimplePieceConfig this[int key] => _dataMap[key];


}

}

