
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbSkillConfig : TbBase
{
    private readonly System.Collections.Generic.Dictionary<int, SkillConfig> _dataMap = new System.Collections.Generic.Dictionary<int, SkillConfig>();
    private readonly System.Collections.Generic.List<SkillConfig> _dataList = new System.Collections.Generic.List<SkillConfig>();
    
    public void Deserialize(byte[] bytes)
    {
        _dataMap.Clear();
        _dataList.Clear();
        ByteBuf _buf = new ByteBuf(bytes);
        int n = _buf.ReadSize();
        for(int i = n ; i > 0 ; --i)
        {
            SkillConfig _v;
            _v = global::cfg.SkillConfig.DeserializeSkillConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SkillConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SkillConfig> DataList => _dataList;

    public SkillConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SkillConfig Get(int key) => _dataMap[key];
    public SkillConfig this[int key] => _dataMap[key];


}

}

