
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TestBean : Luban.BeanBase
{
    public TestBean(ByteBuf _buf) 
    {
        {int n0 = _buf.ReadSize(); Skills = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Skills.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Attrs = new System.Collections.Generic.Dictionary<int, float>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); float _v0;  _v0 = _buf.ReadFloat();     Attrs.Add(_k0, _v0);}}
    }

    public static TestBean DeserializeTestBean(ByteBuf _buf)
    {
        return new TestBean(_buf);
    }

    public readonly System.Collections.Generic.List<int> Skills;
    public readonly System.Collections.Generic.Dictionary<int, float> Attrs;
   
    public const int __ID__ = -1082681470;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
        + "Attrs:" + Luban.StringUtil.CollectionToString(Attrs) + ","
        + "}";
    }
}
}

