//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
public sealed partial class UIConfig :  Bright.Config.BeanBase 
{
    public UIConfig(ByteBuf _buf) 
    {
        UIType = (UIType)_buf.ReadInt();
        Name = _buf.ReadString();
        PrefabName = _buf.ReadString();
        UIWindowType = (UIWindowType)_buf.ReadInt();
        PostInit();
    }

    public static UIConfig DeserializeUIConfig(ByteBuf _buf)
    {
        return new UIConfig(_buf);
    }

    public UIType UIType { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 资源名字
    /// </summary>
    public string PrefabName { get; private set; }
    /// <summary>
    /// 窗口类型
    /// </summary>
    public UIWindowType UIWindowType { get; private set; }

    public const int __ID__ = 202324726;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "UIType:" + UIType + ","
        + "Name:" + Name + ","
        + "PrefabName:" + PrefabName + ","
        + "UIWindowType:" + UIWindowType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}