
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class UIConfig : Luban.BeanBase
{
    public UIConfig(ByteBuf _buf) 
    {
        UIType = (UIType)_buf.ReadInt();
        Name = _buf.ReadString();
        PrefabPath = _buf.ReadString();
        UIWindowType = (UIWindowType)_buf.ReadInt();
    }

    public static UIConfig DeserializeUIConfig(ByteBuf _buf)
    {
        return new UIConfig(_buf);
    }

    public readonly UIType UIType;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 资源名字
    /// </summary>
    public readonly string PrefabPath;
    /// <summary>
    /// 窗口类型
    /// </summary>
    public readonly UIWindowType UIWindowType;
   
    public const int __ID__ = 202324726;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "UIType:" + UIType + ","
        + "Name:" + Name + ","
        + "PrefabPath:" + PrefabPath + ","
        + "UIWindowType:" + UIWindowType + ","
        + "}";
    }
}
}

