
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial struct vec3int
{
    public vec3int(ByteBuf _buf) 
    {
        X = _buf.ReadInt();
        Y = _buf.ReadInt();
        Z = _buf.ReadInt();
    }

    public static vec3int Deserializevec3int(ByteBuf _buf)
    {
        return new vec3int(_buf);
    }

    public readonly int X;
    public readonly int Y;
    public readonly int Z;
   

    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "z:" + Z + ","
        + "}";
    }
}
}

