// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Player.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Message
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BasePlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint playerId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"avatar")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Avatar { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"level")]
        public uint Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SCPlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public BasePlayerInfo Info { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long registerTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"mail")]
        public uint Mail { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
